/// <reference types="jest" />
import { CORE_ROUTE_POLICIES_MEDUSA_VERSION, coreRoutePolicies } from '../core-route-policies'

// eslint-disable-next-line @typescript-eslint/no-var-requires
const { harvest, canonicalKey, installedVersion } = require('../../../scripts/harvest-core-route-policies.cjs')

/**
 * The pinned core-route map is generated by a hand-run script, so nothing but
 * this test stands between it and silent rot: a Medusa upgrade that adds,
 * removes, or re-gates an admin route leaves the checked-in map stale, and a
 * stale map fails *open* — an ungated route simply passes.
 *
 * Structural, not textual: the generator emits JSON and the checked-in file is
 * prettier-formatted, so a text diff is pure noise.
 */
describe('pinned core route map is in sync with the installed Medusa', () => {
	it('records the version it was generated from', () => {
		expect(CORE_ROUTE_POLICIES_MEDUSA_VERSION).toMatch(/^\d+\.\d+\.\d+/)
	})

	it('was generated from the Medusa version currently installed', () => {
		expect(CORE_ROUTE_POLICIES_MEDUSA_VERSION).toBe(installedVersion())
	})

	it('matches what regenerating from the installed package would produce', () => {
		const { entries } = harvest()

		const generated = new Set<string>(entries.map(canonicalKey))
		const pinned = new Set<string>(coreRoutePolicies.map(canonicalKey))

		const missing = [...generated].filter(key => !pinned.has(key)).sort()
		const extra = [...pinned].filter(key => !generated.has(key)).sort()

		// Reported together, and as paths rather than a count, so the failure says
		// what to do about it rather than only that something moved.
		expect({ missingFromPinnedFile: missing, noLongerInMedusa: extra }).toEqual({ missingFromPinnedFile: [], noLongerInMedusa: [] })
	})
})
